---
- name: Criando o Security Group
  local_action:
    module: ec2_group
    name: "{{ sec_group_name }}"
    description: sg remote da massa
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
      rule_desc: SSH da massa vindo de casa
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall


- name: Criando a instancia EC2
  local_action: ec2
    group="{{ sec_group_name }}"
    instance_type="{{ instance_type }}"
    image="{{ image  }}"
    profile="{{ aws_profile }}"
    wait=true
    region="{{ aws_region }}"
    keypair="{{ keypair }}"
    count="{{ count_instances}}"
  register: ec2


- name: Add instancia para o inventario temporario
  add_host: name="{{ item.public_ip}}" groups=kubernetes
  with_items: "{{ ec2.instances }}"


- name: Add o IP publico das instancias no arquivo hosts do ansible
  local_action: lineinfile
    dest="./hosts"
    regexp="{{ item.public_ip }}"
    insertafter="[kubernetes]" line="{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}" 

- name: Add o IP privado das instancias no arquivo hosts do ansible
  local_action: lineinfile
    dest="./hosts"
    regexp="{{item.private_ip}}"
    insertafter="[kubernetes]" line="{{ item.private_ip }}"
  with_items: "{{ ec2.instances}}"  


- name: Esperando o SSH
  local_action: wait_for
    host="{{ item.public_ip }}"
    port=22
    state="started"
  with_items: "{{ ec2.instances }}"

#olhar isso dps

- name: Adicionando uma tag na instancia
  local_action: ec2_tag resource={{ item.id }} region={{ aws_region }} profile={{ aws_profile }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: ansible-{{ item.ami_launch_index|int + 1 }}
