---
- name: Criando o diretorio do app
  file: path={{item}} state=directory
  with_items:
    - /opt/giropops
    - /opt/giropops/logs
    - /opt/giropops/conf
  register: criando_diretorios

- name: Copiando o arquivo de deploy para o host
  template:
    src: app-v1.yaml.j2
    dest: /opt/giropops/app-v1.yaml
    owner: root
    group: root
    mode: 0644
  register: copiando_template

- name: Copiando o arquivo de service da app para o host
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'service_app.yaml', dest: '/opt/giropops/service_app.yaml'}
  register: copiando_service_file

- name: Executando o deploy da App Giropops
  shell: kubectl apply -f /opt/giropops/app-v1.yaml
  register: deploy_app

- name: Criando o Service da App Giropops
  shell: kubectl apply -f /opt/giropops/service_app.yaml
  register: deploy_svc_app


